### PR TITLE
Switch to rich-message module. Closes #65

### LINKED ISSUE #65: Create new repo moose-team/enrich-message for rich-message.js
It feels like `/lib/rich-message.js` could be a nice little separate module that could be useful outside of `friends` too.

Any thoughts around separating it into another module at this time? Maybe `moose-team/enrich-message`? Or is this still premature?

### PR DESCRIPTION
**Pull request by Flet**
Please review!

- removed `lib\rich-message.js`
- moved html-to-vdom conversion to `lib/elements/messages.js` as it was the only place .vdom was used
  - is this ok? Should this be on its own?
- dependencies updated

History preserved at https://github.com/moose-team/rich-message :grin:

### CODE REVIEW

**Comment by ngoldman** [comment]
Looks OK to me. I foresee further refactoring of rich-message to make it less geared towards friends and more useful in other contexts in the future but this is a great start. Decoupling, modularity, compositionality, always good :+1:

**Comment by shama** [comment]
:+1:

**Comment by ngoldman** [comment]
merged :+1:

**Comment by feross** [comment]
Nice!!

**Pull request closed without merging**
