### PR TITLE
Show active and idle users

### PR DESCRIPTION
**Pull request by Flet**
A small change to create separate lists of "active" and "idle" users. Active users are defined as a user who sent a message in the last 60 minutes.

img

### CODE REVIEW

**Comment by ngoldman** [comment]
@Flet does sorting get rerun on render? Is this `virtual-dom` magic?

**Comment by bcomnes** [comment]
Cool!

**Comment by Flet** [comment]
Sort is the same as it was before (sorting on every render call):
https://github.com/moose-team/friends/pull/121/files#diff-d0eabe45ccf8aed55b51591c3ebfaf3dR18

**Comment by alberrrrt** [comment]
What if 60 min to decrease to 25, ah?

**Pull request merged**
