### PR TITLE
Added badges

### PR DESCRIPTION
**Pull request by bcomnes**
It looks like someone needs to clear out the travis node_modules cache... seen this a few times before.  Not sure what the deal is

### CODE REVIEW

**Comment by beaugunderson** [comment]
i think @maxogden disabled travis, i did notice it was failing due to `standard` not being accessible the other day

**Comment by bcomnes** [comment]
Disabling caching all together might fix it as well.

**Comment by beaugunderson** [comment]
oh i see what you're saying; i'll clear the caches right meow

**Comment by beaugunderson** [comment]
hmm cache cleared but failing with a [different error](https://travis-ci.org/moose-team/friends/builds/60321860) now

**Comment by beaugunderson** [comment]
oh, --depth=50 was specified and the commit it's trying to build is >50 commits ago

**Comment by beaugunderson** [comment]
sweet, it's green

**Comment by beaugunderson** [comment]
:sparkles:

**Pull request merged**
