### PR TITLE
add multicast swarm

### PR DESCRIPTION
**Pull request by beaugunderson**
i also added a `npm run build-for-electron` that rebuilds leveldb and mdns...

would be great if a couple of people could test this one! (bonus points if two
people can test locally to verify the multicast swarm works somewhere other
than my laptop)

:sparkles:

### CODE REVIEW

**Comment by bcomnes** [comment]
I'll try to test it out.

**Comment by beaugunderson** [comment]
(rebased)

**Comment by bcomnes** [comment]
Hrmm... just getting a blank electron window

**Comment by beaugunderson** [comment]
check debug.log? (also pull that branch again, i rebased it a minute ago to
fix the conflicts)

**Comment by bcomnes** [comment]
Only output on the terminal is:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v89Signature3NewEPNS_7IsolateENS_6HandleINS_16FunctionTemplateEEEiPS5_
  Referenced from: /Users/bret/Documents/projects/friends/node_modules/mdns-swarm/node_modules/mdns/build/Release/dns_sd_bindings.node
  Expected in: dynamic lookup
dyld: Symbol not found: __ZN2v89Signature3NewEPNS_7IsolateENS_6HandleINS_16FunctionTemplateEEEiPS5_
  Referenced from: /Users/bret/Documents/projects/friends/node_modules/mdns-swarm/node_modules/mdns/build/Release/dns_sd_bindings.node
  Expected in: dynamic lookup
```

**Comment by beaugunderson** [comment]
oh, run `npm run build-for-electron` to fix, sorry

**Comment by ngoldman** [comment]
Does this add another rebuild step necessary for DB changes? If so we might as well generalize the task to `npm run rebuild` and save ourselves some typing?

**Comment by beaugunderson** [comment]
that's what I did :)

rebuild is already a task in npm so I put both leveldb and mdns underneath build-for-electron

**Comment by ngoldman** [comment]
Ah, thanks for dropping the knowledge! Didn't know rebuild was already a thing.

**Comment by beaugunderson** [comment]
no prob, we didn't know it was the other day either; it started off named that and then got renamed

**Comment by bcomnes** [comment]
This was with `npm run build-for-electron`.  I'm running iojs and updated npm using pangyp.  Maybe part of the problem?  I'll try with plain node this evening.

**Comment by beaugunderson** [comment]
weird; try npm install -g node-gyp-install; node-gyp-install

that's what I do under iojs

**Comment by bcomnes** [comment]
ok i will try that... friggin gyp

**Comment by bcomnes** [comment]
Trying again

**Comment by ngoldman** [comment]
Got it working locally with @bcomnes ... it's definitely a little finicky/buggy tough.

1. Got a "accept incoming network connections from Electron Helper.app" dialog
2. Seeing a fair number of log errors:

```
∴ ng@crimelab ~/dev/github/friends (add-multicast) $ npm start

> friends@1.0.0 start /Users/ng/dev/github/friends
> npm run build-css && electron index.js 2>&1 | silence-chromium


> friends@1.0.0 build-css /Users/ng/dev/github/friends
> mkdirp dist && stylus -u nib css/app.styl -o dist/ -c

  compiled dist/app.css
[16225:0502/155108:WARNING:dns_config_service_posix.cc(292)] Failed to read DnsConfig.
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(160)] "Uncaught Error: type friends-scramble has more than 15 characters", source: /Users/ng/dev/github/friends/node_modules/mdns-swarm/node_modules/mdns/lib/service_type.js (160)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[16225:0502/155109:INFO:CONSOLE(160)] "Uncaught Error: type friends-scramble has more than 15 characters", source: /Users/ng/dev/github/friends/node_modules/mdns-swarm/node_modules/mdns/lib/service_type.js (160)
[16225:0502/155110:INFO:CONSOLE(73)] "getaddrinfo ENOTFOUND github.com github.com:443", source: /Users/ng/dev/github/friends/app.js (73)
[16225:0502/155110:INFO:CONSOLE(185)] "→ GET err /connectivity: Error: connect ENETUNREACH 169.254.52.211:60180 - Local (0.0.0.0:52674)", source: /Users/ng/dev/github/friends/node_modules/mdns-swarm/mdns-swarm.js (185)
[16225:0502/155110:INFO:CONSOLE(185)] "→ GET err /connectivity: Error: connect ENETUNREACH 169.254.52.211:60179 - Local (0.0.0.0:52675)", source: /Users/ng/dev/github/friends/node_modules/mdns-swarm/mdns-swarm.js (185)
[16225:0502/155110:INFO:CONSOLE(185)] "→ GET err /connectivity: Error: connect ENETUNREACH 169.254.52.211:60180 - Local (0.0.0.0:52676)", source: /Users/ng/dev/github/friends/node_modules/mdns-swarm/mdns-swarm.js (185)
[16225:0502/155110:INFO:CONSOLE(185)] "→ GET err /connectivity: Error: connect ENETUNREACH 169.254.52.211:60179 - Local (0.0.0.0:52677)", source: /Users/ng/dev/github/friends/node_modules/mdns-swarm/mdns-swarm.js (185)
```

Pretty cool to see it working at all though. :+1:

**Comment by ngoldman** [comment]
@beaugunderson actually disregard that last one, it was actually happening over bluetooth. When we disabled bluetooth nothing came through :(

**Comment by bcomnes** [comment]
This is what saw:

```
Bret-MBR:friends bret$ npm start

> friends@1.0.0 start /Users/bret/Documents/projects/friends
> npm run build-css && electron index.js 2>&1 | silence-chromium


> friends@1.0.0 build-css /Users/bret/Documents/projects/friends
> mkdirp dist && stylus -u nib css/app.styl -o dist/ -c

  compiled dist/app.css
[10170:0502/155705:WARNING:dns_config_service_posix.cc(292)] Failed to read DnsConfig.
[10170:0502/155706:INFO:CONSOLE(73)] "Request to https://api.github.com/search/users?q=bcomnes%40gmail.com%20in%3Aemail failed", source: /Users/bret/Documents/projects/friends/app.js (73)
[10170:0502/155706:INFO:CONSOLE(160)] "Uncaught Error: type friends-moose-team has more than 15 characters", source: /Users/bret/Documents/projects/friends/node_modules/mdns-swarm/node_modules/mdns/lib/service_type.js (160)
[10170:0502/155706:INFO:CONSOLE(160)] "Uncaught Error: type friends-moose-team has more than 15 characters", source: /Users/bret/Documents/projects/friends/node_modules/mdns-swarm/node_modules/mdns/lib/service_type.js (160)
[10172:0502/155712:ERROR:rtc_peer_connection_handler.cc(1027)] Error processing ICE candidate.
[10172:0502/155712:ERROR:rtc_peer_connection_handler.cc(1027)] Error processing ICE candidate.
```

**Comment by beaugunderson** [comment]
ahhh, i wasn't aware of the 15 character limit for one (i guess i'll hash them or put the channel in a TXT key)
the ICE candidate errors i see regardless of multicast sometimes

**Comment by bcomnes** [comment]
We also didn't test with a router.... just the `Create Network...` network option that OS X offers.  Maybe with an internet-less router we would have had success.

**Comment by beaugunderson** [comment]
will revisit this if friends becomes active again :)

**Pull request closed without merging**
