### PR TITLE
add UI for help with GitHub authentication

### PR DESCRIPTION
**Pull request by beaugunderson**
I imagine there's a better way to organize things than I did; let me know if
things should get moved around.

### CODE REVIEW

**Comment by beaugunderson** [comment]
looks like this (but a little nicer):

screenshot

**Comment by maxogden** [comment]
i say merge!

**Comment by beaugunderson** [comment]
:cat2: :sparkles: :sparkles: :sparkles:

**Comment by feross** [comment]
nice!

**Pull request merged**
