### PR TITLE
code style and minor textarea fix

### PR DESCRIPTION
**Pull request by Adjective-Object**
addresses part of #62

### CODE REVIEW

**Comment by beaugunderson** [comment]
what does `resize: none` do to multi line messages? (shift-enter)

**Comment by Adjective-Object** [comment]
nothing.
The `resize: ...` property only adjusts the resize carat's (handle's?) behavior.

**Comment by beaugunderson** [comment]
ohhh gotcha; sorry, thought this was addressing a different part of #62!

**Comment by beaugunderson** [comment]
:sparkles:

**Pull request merged**
