### PR TITLE
more explicit setup / installation steps

### PR DESCRIPTION
**Pull request by noffle**
The current README has headings for `Logging In` and `Building`, and doesn't make the installation/running instructions too explicit for first-time readers (as per #147).

#146 is a good next step for simplifying this process.

### CODE REVIEW

**Comment by ngoldman** [comment]
:+1:

Might make sense to split these instructions into **Building**, **Running**, and **Logging in** (in that order) under the **Installation** header.

**Comment by ngoldman** [comment]
A typical split in READMEs is `Install` & `Usage` -- maybe a list of requirements and instructions on building could go under `Install`, and running and logging in could go under `Usage`?

**Comment by noffle** [comment]
Strongly agree with everything you've said. :+1:  Updated!

**Comment by ngoldman** [comment]
Much more clear, thanks @noffle! :sparkles: 1000 points :sparkles:

**Pull request merged**
