### PR TITLE
Move command switch to command.js

### PR DESCRIPTION
**Pull request by bcomnes**
This is a simple dropin patch that moves the command switch to its own file.  We can make it more OO if we want, but for now lets just get all of this out of app.js

### CODE REVIEW

**Comment by bcomnes** [comment]
This should also get the ball rolling on https://github.com/moose-team/friends/issues/117

**Comment by beaugunderson** [comment]
:+1:

**Comment by bcomnes** [comment]
One question I have:  This is just a simple closure.... looks like there are some fancier prototype chain stuff going on in app.js.   Should I be passing `self` around differently?

**Comment by ngoldman** [comment]
@bcomnes I think it's sufficient for now, can be refactored as necessary :+1:

**Comment by ngoldman** [comment]
@bcomnes Adding you to moose-team!

**Pull request merged**
