### PR TITLE
Added command aliases and leaveall command

### LINKED ISSUE #107: add /alias command
and yea, would be good to follow irc signature

### PR DESCRIPTION
**Pull request by pokemonmegaman**
Added two new commands: `/leaveall` (which also can be called with `/wcall` or `/partall`) which leaves all channels except friends, and `/alias` to resolve #107 .
Command aliases work by using `/alias <name of alias> <command to execute>` and are called by `/<name of alias>`.  Aliases are stored locally using leveldb.

### CODE REVIEW

**Comment by ngoldman** [comment]
Thanks @pokemonmegman! Looks like a very clean implementation to me.

One question: is there a convention for listing and  removing aliases we can add as well?

**Comment by pokemonmegaman** [comment]
It might not be a bad idea just to implement a `/help` command for listing all commands.  As for deleting commands, maybe `/rmalias <name of alias>`?

**Comment by ngoldman** [comment]
@pokemonmegaman both those ideas sound good for now. I hunted around a bit and couldn't find any great conventions for removing an alias in IRC clients. :+1:

**Comment by pokemonmegaman** [comment]
for listing commands, we should have a way of adding messages that only show up locally, because we don't want to send our list of aliases to the rest of the server (that would be annoying).  that being said, we really should externalize all the commands into another file, and it would be nice if we could add in descriptions for each one of the commands so we can more easily create `/help`

**Comment by ngoldman** [comment]
@pokemonmegaman just merged a commit from @bcomnes refactoring commands a bit, can you rebase please? :grin:

**Comment by pokemonmegaman** [comment]
Yep, that can certainly be done.

**Comment by pokemonmegaman** [comment]
Alright, should be good now.

**Comment by ngoldman** [comment]
@pokemonmegaman :+1:

**Comment by tunnckoCore** [comment]
yeaaah! looks great :) :+1:

**Pull request merged**
