### PR TITLE
centralize config, store db & keys in config path

### PR DESCRIPTION
**Pull request by ungoldman**
using `application-config-path@^0.1.0` for OS-friendly config path

note this means if you want to keep history you need to copy `friendsdb` and `public-keys` from the project directory to the application config path, which will be...

Platform | Location
--- | ---
OS X | `~/Library/Application Support/Friends/config.json`
Linux (XDG) | `$XDG_CONFIG_HOME/Friends/config.json`
Linux (Legacy) | `~/.config/Friends/config.json`
Windows (> Vista) | `%LOCALAPPDATA%/Friends/config.json`
Windows (XP, 2000) | `%USERPROFILE%/Local Settings/Application Data/Friends/config.json`

### CODE REVIEW

**Comment by ungoldman** [comment]
merging, review welcome

**Comment by beaugunderson** [comment]
i like the idea, though i like to use $XDG_CONFIG_PATH on OS X as well... probably not a big deal though? (people can always symlink)

**Comment by ungoldman** [comment]
@beaugunderson what is $XDG_CONFIG_PATH used for in OS X? This PR is based on what we did in https://github.com/feross/webtorrent-app/blob/master/config.js and the config path is determined by https://github.com/LinusU/node-application-config-path.

**Comment by beaugunderson** [comment]
whatever the user sets it to (~/.config in my case)

**Comment by ungoldman** [comment]
Yeah I guess my instinct is to just use the standard config path for the OS and let users override if they really want to. Would you want Friends to test for an env var before setting `CONFIG_PATH`?

**Pull request merged**
